# Generated by Django 4.2.4 on 2023-08-27 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskName',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Глобальной цели')),
                ('name', models.CharField(max_length=255, verbose_name='Название глобальной цели')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Inter_Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID цели')),
                ('task_text', models.CharField(max_length=255, verbose_name='Промежуточная цель')),
                ('global_task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.taskname')),
            ],
        ),
    ]
