# Generated by Django 4.2.4 on 2023-09-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_taskname_inter_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='inter_task',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='Завершено'),
        ),
    ]
