# Generated by Django 4.2.4 on 2023-09-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_inter_task_is_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskname',
            name='tasks_count',
            field=models.IntegerField(default=0, verbose_name='Количество подзадач'),
        ),
    ]
